dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: 3tWdNtb6Osnzu57VsG5CiquaTQE0f1MSrtTiBHRGROQUeQFBb2ckIQj5wrNU3+LA92SQ7UdVCUFNH/JbOlJxStyie/P8Glmd1LKi+K6rbpXnOQKB5pXkpYbm4gHW/JI0tZX5bwqXoIOdyzfajw48n78K18pdjmy/EzA4URWJozi5CsCNjQDcyy6WEjWPEszbW8Um/nMoAdPkOVokHDpyV3ZHEaJBJ/66kMIU8NzzvlsN2vTLvFr5F6T3usMS6PGmLOeCiGaZvtg49sdsgUQzUcZJO76okNHqpzv199hLo+QsxGaTsa7TFCsOSMg5i84ZrZNIIHxQoGTZ/bvmjMnU2a4NrOwG+Px3stfW0BEgeREqP4W+bmN72jLwDRFaxw89jhsdKH/52O8XjKtWkvDPxglYnC1JbaDbo6eNUEicTmy7LfWVtg9+wZNXJGp1AqvFuQKU19Jy62GUVLJ2u84IsTGBE5v2T3VlSrnlyGE1p0z+FrayShpH4fRV6VI469DBOaDju1Fg7MyTx4pBVxaYYkqEWyrLyTFqRj4I/4VRpPDesJvAjkwuGLyY1a1JWJyWIWBnQNTFTSSzNcwdpz5eM8gI9x9+EwYVk2eYodq0NakMOOGO5bleqP0xM9/5p1R7bBrmqNUcY7Pian2ZyoEpdabpVd3YDfjAJGry8DKZl24=
  - secure: D5Y7hDjmCYIyRPy6pzvENjR08NxHufBoEDEyNUzjBEEww1AIjn8uYnRW8saCK/LMQsg2aaG7QDNtDjDaQ8732YHt4W42TB7fAoJal3HdsIvtRIQ7x5x/Xb9htFMUxNmvbVUiTfS7jbpDjn+zdmqQ0EObBktREhVrohhV9pSCt6vOZ1Lpcww4LUl8Np8zw3W5erDVNKytzRyn1k2rb3LsU0mPso4B2m9bKzvLmBSIRQDNvNoUSvjFFQDE86fBTKu/py8ccBOngQwpjslxQxxFJOsEs/XuVDuES4rZMQHCljdBUIPxEkLYFJ0ZI4BPJfIXICBDGUzwf+MKcOTWy5DQokMRWVGwmdzO6hcu+VHB68Fi3BdSXtq+KyXhUQ1+CRu16rNjYTlkNaJYh82DAsn3x9O0GTlS1xjOlrS5a47zvqKkF0Vvjae4+dzhBbY8aHz+5kaWedYnC1svHgNUSgB0QQxXjO+kbqYdDVqXQDe12Tpa8/+ALLHPjqE/tVvSJXQhGcWi9SRnOlZFxuQq5j3qv8PVZqxXUv3cEbeBEBtEGpfyug8cHpuoygL7G3nYDcHpSNoue6LY1IUWSbzcjWYSJgp093ydJXDY1ccAUuZ8v3efoDcoevOQr7WLvsUbGSUcNHJLGi/dbVHb32cIalZDS+NolZKBUn9JQ/eg8UdmqhI=
  - secure: D90v5GGZUEn/GY/QH6AqDXqo0tV+qY+Y8udxLP72wQuDBEm0yn6vInTkm+BCu75QbzB71DFMVq74SW4iAIF2GJ9ut2ueRY6dd0pDW1SqFsDQ6UtiXHECRf0wtkD+PFWEUco4iUHR5MvO3SiZI+LS+MV+9V4uK8HHJiwqw4RpOhkiUTJbEW4T41SdkKBphPR071EKij26OhpCQY1rBknC4GC4kmpSNWZIMgYXP+bWj9bvCBZnHSUBuUq3u2+o156rVOGm+OVAvWuoly5AXxzVqQLDlQl7LGqaYR9OVZQkks01e/yA0ZVNPk23hAv14+17lcSzAD4QS5/uJHRItlg2R3woXSlwu2gLMsQHsLzTbdCWv1/hNgweldgeA2QLXwLP/y94qGoRBxVom16o4l+soC5wjBhhmnxyYx9u61ayiJmyQlvKHZvRbJnU1QdRnmViB0FAvqevmAyXV1vIpONsXl3B3XjifTSGMrUjmc9jSZS3r0LY/wrYILIW9Org1U8daphXF3t850dpb22QlzmcxpdDWEi2H3RyevdwO4VpptVEc+qFVSmmiJyd+LBF4N3Vj1IdwLXCkIk784DPkwxY0lOVugJproWAKsEbvZLr77Lbf3XFZh1RJ2VvmLMjC0AcDeC6Ewz4poS1oOhgLIeamFa9Fm5VNIckzkIlbqeY4kc=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
